### ISSUE TITLE
LINEA DEL TIEMPO SOBRE LA WEB 1.0, 2.0 Y 3.0

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/actividad-7-irvinjs22620075#1]
[LINEA DE TIEMPO SOBRE LA WEB 1.0, 2.0 Y 3.0.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-irvinjs22620075/files/9792569/LINEA.DE.TIEMPO.SOBRE.LA.WEB.1.0.2.0.Y.3.0.pdf)

**Comment by 11042002** [comment]
Tu calificación es de: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
